### ISSUE TITLE
Help on usage

### ISSUE THREAD

**Issue by gioppoluca** [kandashi/custom-classes#1]
Hi trying to understand how to use this module.
Do I have to add the part that point to module.js also in my compendium so that it will load also the list of my custom classes?
Can you please explain a bit more the sub-class "stuff" since it seems that Fopundry really do not have the concept so how can you implement a sub-class?

**Comment by MaxPat931** [comment]
@gioppoluca Here's a basic guide on how I got my subclass to work
https://imgur.com/a/Z4zoRFo
