### ISSUE TITLE
Usage with Custom Class Item in Personal Compendium

### ISSUE THREAD

**Issue by GarebearNF** [kandashi/custom-classes#4]
I see how this would work with adding a subclass to an existing 5e class, but can this module reference a class item that I create in order to put together an entirely homebrewed class? What would that look like in the config?

**Comment by MaxPat931** [comment]
@GarebearNF

You can look to the existing Class/subclass structure to intuit this, but it should look something like the following, replace the text in all caps following the format of the original file, and of course add lines for the appropriate levels.
I also found that the CLASS doesn't like multiple words, so **"blood-hunter": {** for instance, the name of the Class item in Foundry needs to include that - so, **Blood-Hunter**.

  ```
  "CLASS": {
	    "subclasses": {
		"SUBCLASS-NAME": {
		    "label": "SUBCLASS NAME",
		    "source": "OPTIONAL",
		    "features": {
			"3": ["Compendium.LINK.HERE", "Compendium.LINK.HERE"],
			"5": ["Compendium.LINK.HERE", "Compendium.LINK.HERE"]
		    }
		}
	    "features": {
			"1": [""Compendium.LINK.HERE""],
			"2": [""Compendium.LINK.HERE""],
			"3": [""Compendium.LINK.HERE""]
	    }
	},
  ```

**Comment by GarebearNF** [comment]
Thanks for the response. That's the structure I have, but when I apply the class to a character sheet, nothing happened. I discovered that there was an extra line in the module.js from a stray copy/paste that was erroring the module. 

It's all set now!
