### ISSUE TITLE
This Doesn't Appear to Work in V9

### ISSUE THREAD

**Issue by webmaster94** [kandashi/custom-classes#6]
I am not sure if I am doing something wrong or if there is something wrong in the code, but this does not appear to work in Foundry v9. I never messed around with this in v8 so I am not even sure if it worked in that version. Would you be willing to assist on this? 

Foundry Virtual Tabletop: Version 9, 9.242
Game System: dnd5e, 1.5.7

**Comment by kandashi** [comment]
Nothing has changed from v8 to v9 regarding this module. Make sure your class file is valid and the data is formatted correctly.

**Comment by webmaster94** [comment]
So this is the class I added to module.js. Do you know what I am doing wrong?

![image](https://user-images.githubusercontent.com/85364225/150703490-abd5de6b-63b5-488a-87f4-7e9e92333cfd.png)

I validated the JS and I am not getting any errors in the console. I ran find the culprit to ensure that there are no module conflicts.

**Comment by kandashi** [comment]
You cant have spaces in the class name like that

**Comment by webmaster94** [comment]
Can you have special characters such as "-" or "()"?
